workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 60
    environment:
      node: 20
      cocoapods: default
    scripts:
      - node -v && npm -v
      - npm ci
      # iOS platformu yoksa oluştur (Podfile burada gelir)
      - if [ ! -d ios ]; then npx cap add ios; fi
      # (varsa sorun değil; add yoksa sync tek başına yeterli olmayabilir)
      - npx cap sync ios
      - cd ios/App
      # Podfile gerçekten var mı kontrol et (debug için listeler)
      - ls -la
      - if [ ! -f Podfile ]; then echo "ERROR: Podfile missing in ios/App"; exit 1; fi
      - pod install
      - xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -archivePath $CM_BUILD_DIR/build/App.xcarchive archive
      - xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/build/App.xcarchive -exportOptionsPlist ../../exportOptions.plist -exportPath $CM_BUILD_DIR/build
    artifacts:
      - build/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
