workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 60
    environment:
      node: 20
      cocoapods: default
    scripts:
      - |
          echo "Node version:"
          node -v
          echo "NPM version:"
          npm -v

      - npm ci

      # iOS platformu yoksa oluştur (Podfile burada gelir)
      - |
          if [ ! -d "ios" ]; then
            npx cap add ios
          fi

      # Web dosyaları ve pluginleri iOS projesine senkronize et
      - npx cap sync ios

      # CocoaPods
      - |
          cd ios/App
          pod repo update
          pod install

      # Arşiv (workspace'e tam yol verdik)
      - xcodebuild -workspace ios/App/App.xcworkspace -scheme App -configuration Release -archivePath $CM_BUILD_DIR/build/App.xcarchive archive

      # IPA oluştur ve dışa aktar (repo kökündeki exportOptions.plist kullanılır)
      - xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/build/App.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $CM_BUILD_DIR/build

    artifacts:
      - build/*.ipa

    publishing:
      app_store_connect:
        api_key: -----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgEFGjpWz/qld5quqx
7LA3tvZz5K1LaIVZBH4WeeI3ROigCgYIKoZIzj0DAQehRANCAARZRrQqDVuRSsxU
k1WJr95F9mq/vrAWDq9kfv/b+qTMP9LvNWtjsmGvhSIfLLbLRlw58OTuveSPfGRN
pQGS1fW7
-----END PRIVATE KEY----- 
        key_id: 55YN7MXP9Y
        issuer_id: e5838a54-e0d7-4d54-9071-15c39c7ab252
        submit_to_testflight: true
