workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 60
    environment:
      node: 20
      cocoapods: default
    scripts:
      # Versiyon bilgisini log'a yaz
      - echo "Node: $(node -v)  NPM: $(npm -v)"

      # NPM bağımlılıkları
      - npm ci

      # iOS platformu yoksa oluştur (Podfile bu adımda gelir)
      - |
        if [ ! -d "ios" ]; then
          npx cap add ios
        fi

      # Web dosyalarını ve pluginleri iOS projesine senkronize et
      - npx cap sync ios

      # Pod kurulumunu ios/App klasöründe yap
      - |
        cd ios/App
        pod install

      # Arşivleme (workspace tam yolu ile)
      - xcodebuild -workspace ios/App/App.xcworkspace -scheme App -configuration Release -archivePath $CM_BUILD_DIR/build/App.xcarchive archive

      # IPA oluşturup dışa aktar (repo kökündeki exportOptions.plist'i kullan)
      - xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/build/App.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $CM_BUILD_DIR/build

    artifacts:
      - build/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
