workflows:
  ios_capacitor_store:
    name: "iOS • Capacitor • App Store"
    instance_type: mac_mini_m2

    environment:
      node: 18
      xcode: 15.4
      cocoapods: default
      vars:
        # Projene göre doğru yolu ve şemayı kontrol et:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"

    scripts:
      - name: Decode private key (from B64 to PEM)
        script: |
          if [ -z "$APP_STORE_CONNECT_PRIVATE_KEY_B64" ]; then
            echo "✗ PRIVATE_KEY_B64 MISSING"; exit 1
          fi
          export APP_STORE_CONNECT_PRIVATE_KEY="$(echo "$APP_STORE_CONNECT_PRIVATE_KEY_B64" | base64 -d)"
          echo "$APP_STORE_CONNECT_PRIVATE_KEY" | head -n 1 | grep -q "BEGIN PRIVATE KEY" || { echo "✗ Key not decoded"; exit 1; }
          echo "✓ Private key decoded"

      - name: ENV sanity check
        script: |
          echo "KEY_ID=$APP_STORE_CONNECT_KEY_IDENTIFIER"
          echo "ISSUER_ID=$APP_STORE_CONNECT_ISSUER_ID"
          test -n "$APP_STORE_CONNECT_PRIVATE_KEY" || { echo "✗ PRIVATE_KEY missing"; exit 1; }
          echo "✓ env ok"

      - name: Install & sync Capacitor
        script: |
          npm ci
          npx cap sync ios

      - name: Fetch signing & build .ipa
        script: |
          app-store-connect fetch-signing-files --type IOS_APP_STORE --create
          xcode-project use-profiles
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --archive-flags="-destination 'generic/platform=iOS'"

    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Logs/gym/*.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        # submit_to_testflight: true  # <-- YOK (sadece App Store Connect’e upload)
