workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 60
    environment:
      node: 20
      cocoapods: default
    scripts:
      - |
          echo "Node version:"
          node -v
          echo "NPM version:"
          npm -v

      - npm ci

      # iOS platformu yoksa oluştur (Podfile burada gelir)
      - |
          if [ ! -d "ios" ]; then
            npx cap add ios
          fi

      # Web dosyaları ve pluginleri iOS projesine senkronize et
      - npx cap sync ios

      # CocoaPods
      - |
          cd ios/App
          pod repo update
          pod install

      # Arşiv (workspace'e tam yol verdik)
      - xcodebuild -workspace ios/App/App.xcworkspace -scheme App -configuration Release -archivePath $CM_BUILD_DIR/build/App.xcarchive archive

      # IPA oluştur ve dışa aktar (repo kökündeki exportOptions.plist kullanılır)
      - xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/build/App.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $CM_BUILD_DIR/build

    artifacts:
      - build/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
