workflows:
  ios_capacitor_testflight:
    name: "iOS • Capacitor • TestFlight"
    instance_type: mac_mini_m2

    environment:
      node: 18
      xcode: 15.4
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"

    scripts:
      - name: Decode private key
        script: |
          if [ -z "$APP_STORE_CONNECT_PRIVATE_KEY_B64" ]; then
            echo "✗ PRIVATE_KEY_B64 MISSING"; exit 1
          fi
          export APP_STORE_CONNECT_PRIVATE_KEY="$(echo "$APP_STORE_CONNECT_PRIVATE_KEY_B64" | base64 -d)"
          echo "$APP_STORE_CONNECT_PRIVATE_KEY" | head -n 1 | grep -q "BEGIN PRIVATE KEY" || { echo "✗ Key not decoded"; exit 1; }
          echo "✓ Private key decoded"

      - name: ENV sanity check
        script: |
          echo "✓ ISSUER_ID: ${APP_STORE_CONNECT_ISSUER_ID}"
          echo "✓ KEY_ID   : ${APP_STORE_CONNECT_KEY_IDENTIFIER}"
          [ -n "$APP_STORE_CONNECT_PRIVATE_KEY" ] || { echo "✗ PRIVATE_KEY MISSING"; exit 1; }

      - name: Install & sync Capacitor
        script: |
          npm ci
          npx cap sync ios

      - name: Build .ipa
        script: |
          xcode-project use-profiles
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --archive-flags="-destination 'generic/platform=iOS'"

    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Logs/gym/*.log

    publishing:
      app_store_connect:
        api_key:
          key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID
          private_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true
        release_type: "BETA"
