workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 60
    environment:
      node: 20
      cocoapods: default
      vars:
        BUNDLE_ID: com.kfd.panel

    scripts:
      - npm ci

      - |
          if [ ! -d "ios" ]; then
            npx cap add ios
          fi

      - npx cap sync ios

      - |
          cd ios/App
          pod install
          cd ../../

      # ENV KONTROL – boşsa hemen dur
      - |
          echo "ENV sanity check:"
          test -n "$APP_STORE_CONNECT_ISSUER_ID" && echo "✔ ISSUER_ID OK" || (echo "✖ ISSUER_ID MISSING"; exit 1)
          test -n "$APP_STORE_CONNECT_KEY_IDENTIFIER" && echo "✔ KEY_ID OK" || (echo "✖ KEY_ID MISSING"; exit 1)
          if [ -z "$APP_STORE_CONNECT_PRIVATE_KEY" ]; then echo "✖ PRIVATE_KEY MISSING"; exit 1; else echo "✔ PRIVATE_KEY looks set"; fi

      # Otomatik imzalama (argümanları açıkça geçiriyoruz)
      - keychain initialize
      - |
          app-store-connect fetch-signing-files \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --type IOS_APP_STORE \
            --create \
            "$BUNDLE_ID"
      - keychain add-certificates
      - xcode-project use-profiles

      - xcode-project build-ipa --workspace ios/App/App.xcworkspace --scheme App --export-options-plist exportOptions.plist

    artifacts:
      - build/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
