workflows:
  ios_capacitor_store:
    name: "iOS • Capacitor • App Store"
    instance_type: mac_mini_m2

    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"

    scripts:
      - name: Install & sync Capacitor
        script: |
          npm ci
          npx cap sync ios
      - name: Build IPA
        script: |
          xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -configuration Release -archivePath build/App.xcarchive
          xcodebuild -exportArchive -archivePath build/App.xcarchive -exportPath build/ipa -exportOptionsPlist ios/exportOptions.plist

    artifacts:
      - build/ipa/*.ipa
      - $HOME/Library/Logs/gym/*.log